# https://docs.readthedocs.io/en/latest/config-file/index.html#configuration-file
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx-autodoc-typehints~=1.18.1

