[tool.poetry]
name = "polygon-api-client"
version = "0.0.0"
description = "Official Polygon.io REST and Websocket client."
authors = ["polygon.io"]
license = "MIT"
homepage = "https://polygon.io"
repository = "https://github.com/polygon-io/client-python"
documentation = "https://polygon.io/docs"
keywords = [
  "polygon",
  "free",
  "rest",
  "stock",
  "market",
  "data",
  "api",
  "polygon.io",
  "websocket",
  "client"
]
packages = [
  { include = "polygon" }
]

[tool.poetry.dependencies]
python = "^3.7"
urllib3 = "^1.26.9"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
mypy = "^0.942"
types-urllib3 = "^1.26.13"
httpretty = "^1.1.4"
Sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"
# keep this in sync with docs/requirements.txt for readthedocs.org
sphinx-autodoc-typehints = "^1.18.1"

[build-system]
# so releasing doesn't have to touch the "version" in this file
# we have to use a beta release of poetry and this plugin:
# https://pypi.org/project/poetry-dynamic-versioning-plugin/
requires = ["poetry>=1.2.0b1", "poetry-dynamic-versioning-plugin"]
build-backend = "poetry.masonry.api"

[tool.poetry-dynamic-versioning]
enable = true
style = "semver"
