# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Aggv2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'T': 'str',
        'v': 'int',
        'o': 'int',
        'c': 'int',
        'h': 'int',
        'l': 'int',
        't': 'float',
        'n': 'float'
    }

    attribute_map = {
        'T': 'T',
        'v': 'v',
        'o': 'o',
        'c': 'c',
        'h': 'h',
        'l': 'l',
        't': 't',
        'n': 'n'
    }

    def __init__(self, T=None, v=None, o=None, c=None, h=None, l=None, t=None, n=None):  # noqa: E501
        """Aggv2 - a model defined in Swagger"""  # noqa: E501
        self._T = None
        self._v = None
        self._o = None
        self._c = None
        self._h = None
        self._l = None
        self._t = None
        self._n = None
        self.discriminator = None
        if T is not None:
            self.T = T
        self.v = v
        self.o = o
        self.c = c
        self.h = h
        self.l = l
        if t is not None:
            self.t = t
        if n is not None:
            self.n = n

    @property
    def T(self):
        """Gets the T of this Aggv2.  # noqa: E501

        Ticker symbol  # noqa: E501

        :return: The T of this Aggv2.  # noqa: E501
        :rtype: str
        """
        return self._T

    @T.setter
    def T(self, T):
        """Sets the T of this Aggv2.

        Ticker symbol  # noqa: E501

        :param T: The T of this Aggv2.  # noqa: E501
        :type: str
        """

        self._T = T

    @property
    def v(self):
        """Gets the v of this Aggv2.  # noqa: E501

        Volume  # noqa: E501

        :return: The v of this Aggv2.  # noqa: E501
        :rtype: int
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this Aggv2.

        Volume  # noqa: E501

        :param v: The v of this Aggv2.  # noqa: E501
        :type: int
        """
        if v is None:
            raise ValueError("Invalid value for `v`, must not be `None`")  # noqa: E501

        self._v = v

    @property
    def o(self):
        """Gets the o of this Aggv2.  # noqa: E501

        Open  # noqa: E501

        :return: The o of this Aggv2.  # noqa: E501
        :rtype: int
        """
        return self._o

    @o.setter
    def o(self, o):
        """Sets the o of this Aggv2.

        Open  # noqa: E501

        :param o: The o of this Aggv2.  # noqa: E501
        :type: int
        """
        if o is None:
            raise ValueError("Invalid value for `o`, must not be `None`")  # noqa: E501

        self._o = o

    @property
    def c(self):
        """Gets the c of this Aggv2.  # noqa: E501

        Close  # noqa: E501

        :return: The c of this Aggv2.  # noqa: E501
        :rtype: int
        """
        return self._c

    @c.setter
    def c(self, c):
        """Sets the c of this Aggv2.

        Close  # noqa: E501

        :param c: The c of this Aggv2.  # noqa: E501
        :type: int
        """
        if c is None:
            raise ValueError("Invalid value for `c`, must not be `None`")  # noqa: E501

        self._c = c

    @property
    def h(self):
        """Gets the h of this Aggv2.  # noqa: E501

        High  # noqa: E501

        :return: The h of this Aggv2.  # noqa: E501
        :rtype: int
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this Aggv2.

        High  # noqa: E501

        :param h: The h of this Aggv2.  # noqa: E501
        :type: int
        """
        if h is None:
            raise ValueError("Invalid value for `h`, must not be `None`")  # noqa: E501

        self._h = h

    @property
    def l(self):
        """Gets the l of this Aggv2.  # noqa: E501

        Low  # noqa: E501

        :return: The l of this Aggv2.  # noqa: E501
        :rtype: int
        """
        return self._l

    @l.setter
    def l(self, l):
        """Sets the l of this Aggv2.

        Low  # noqa: E501

        :param l: The l of this Aggv2.  # noqa: E501
        :type: int
        """
        if l is None:
            raise ValueError("Invalid value for `l`, must not be `None`")  # noqa: E501

        self._l = l

    @property
    def t(self):
        """Gets the t of this Aggv2.  # noqa: E501

        Unix Msec Timestamp ( Start of Aggregate window )  # noqa: E501

        :return: The t of this Aggv2.  # noqa: E501
        :rtype: float
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this Aggv2.

        Unix Msec Timestamp ( Start of Aggregate window )  # noqa: E501

        :param t: The t of this Aggv2.  # noqa: E501
        :type: float
        """

        self._t = t

    @property
    def n(self):
        """Gets the n of this Aggv2.  # noqa: E501

        Number of items in aggregate window  # noqa: E501

        :return: The n of this Aggv2.  # noqa: E501
        :rtype: float
        """
        return self._n

    @n.setter
    def n(self, n):
        """Sets the n of this Aggv2.

        Number of items in aggregate window  # noqa: E501

        :param n: The n of this Aggv2.  # noqa: E501
        :type: float
        """

        self._n = n

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Aggv2, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Aggv2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
