# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class CryptoExchange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'type': 'str',
        'market': 'str',
        'name': 'str',
        'url': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'market': 'market',
        'name': 'name',
        'url': 'url'
    }

    def __init__(self, id=None, type=None, market=None, name=None, url=None):  # noqa: E501
        """CryptoExchange - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._market = None
        self._name = None
        self._url = None
        self.discriminator = None
        self.id = id
        self.type = type
        self.market = market
        self.name = name
        self.url = url

    @property
    def id(self):
        """Gets the id of this CryptoExchange.  # noqa: E501

        ID of the exchange  # noqa: E501

        :return: The id of this CryptoExchange.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CryptoExchange.

        ID of the exchange  # noqa: E501

        :param id: The id of this CryptoExchange.  # noqa: E501
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this CryptoExchange.  # noqa: E501

        Type of exchange feed  # noqa: E501

        :return: The type of this CryptoExchange.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CryptoExchange.

        Type of exchange feed  # noqa: E501

        :param type: The type of this CryptoExchange.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["exchange"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def market(self):
        """Gets the market of this CryptoExchange.  # noqa: E501

        Market data type this exchange contains ( crypto only currently )  # noqa: E501

        :return: The market of this CryptoExchange.  # noqa: E501
        :rtype: str
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this CryptoExchange.

        Market data type this exchange contains ( crypto only currently )  # noqa: E501

        :param market: The market of this CryptoExchange.  # noqa: E501
        :type: str
        """
        if market is None:
            raise ValueError("Invalid value for `market`, must not be `None`")  # noqa: E501
        allowed_values = ["crypto"]  # noqa: E501
        if market not in allowed_values:
            raise ValueError(
                "Invalid value for `market` ({0}), must be one of {1}"  # noqa: E501
                .format(market, allowed_values)
            )

        self._market = market

    @property
    def name(self):
        """Gets the name of this CryptoExchange.  # noqa: E501

        Name of the exchange  # noqa: E501

        :return: The name of this CryptoExchange.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CryptoExchange.

        Name of the exchange  # noqa: E501

        :param name: The name of this CryptoExchange.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def url(self):
        """Gets the url of this CryptoExchange.  # noqa: E501

        URL of this exchange  # noqa: E501

        :return: The url of this CryptoExchange.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this CryptoExchange.

        URL of this exchange  # noqa: E501

        :param url: The url of this CryptoExchange.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CryptoExchange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CryptoExchange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
