# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Exchange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'type': 'str',
        'market': 'str',
        'mic': 'str',
        'name': 'str',
        'tape': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'market': 'market',
        'mic': 'mic',
        'name': 'name',
        'tape': 'tape'
    }

    def __init__(self, id=None, type=None, market=None, mic=None, name=None, tape=None):  # noqa: E501
        """Exchange - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._market = None
        self._mic = None
        self._name = None
        self._tape = None
        self.discriminator = None
        self.id = id
        self.type = type
        self.market = market
        self.mic = mic
        self.name = name
        self.tape = tape

    @property
    def id(self):
        """Gets the id of this Exchange.  # noqa: E501

        ID of the exchange  # noqa: E501

        :return: The id of this Exchange.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Exchange.

        ID of the exchange  # noqa: E501

        :param id: The id of this Exchange.  # noqa: E501
        :type: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this Exchange.  # noqa: E501

        The type of exchange this is.<br/> - TRF = Trade Reporting Facility<br/> - exchange = Reporting exchange on the tape   # noqa: E501

        :return: The type of this Exchange.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Exchange.

        The type of exchange this is.<br/> - TRF = Trade Reporting Facility<br/> - exchange = Reporting exchange on the tape   # noqa: E501

        :param type: The type of this Exchange.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["TRF", "exchange"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def market(self):
        """Gets the market of this Exchange.  # noqa: E501

        Market data type this exchange contains  # noqa: E501

        :return: The market of this Exchange.  # noqa: E501
        :rtype: str
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this Exchange.

        Market data type this exchange contains  # noqa: E501

        :param market: The market of this Exchange.  # noqa: E501
        :type: str
        """
        if market is None:
            raise ValueError("Invalid value for `market`, must not be `None`")  # noqa: E501
        allowed_values = ["equities", "indecies"]  # noqa: E501
        if market not in allowed_values:
            raise ValueError(
                "Invalid value for `market` ({0}), must be one of {1}"  # noqa: E501
                .format(market, allowed_values)
            )

        self._market = market

    @property
    def mic(self):
        """Gets the mic of this Exchange.  # noqa: E501

        Market Identification Code  # noqa: E501

        :return: The mic of this Exchange.  # noqa: E501
        :rtype: str
        """
        return self._mic

    @mic.setter
    def mic(self, mic):
        """Sets the mic of this Exchange.

        Market Identification Code  # noqa: E501

        :param mic: The mic of this Exchange.  # noqa: E501
        :type: str
        """
        if mic is None:
            raise ValueError("Invalid value for `mic`, must not be `None`")  # noqa: E501

        self._mic = mic

    @property
    def name(self):
        """Gets the name of this Exchange.  # noqa: E501

        Name of the exchange  # noqa: E501

        :return: The name of this Exchange.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Exchange.

        Name of the exchange  # noqa: E501

        :param name: The name of this Exchange.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def tape(self):
        """Gets the tape of this Exchange.  # noqa: E501

        Tape id of the exchange  # noqa: E501

        :return: The tape of this Exchange.  # noqa: E501
        :rtype: str
        """
        return self._tape

    @tape.setter
    def tape(self, tape):
        """Sets the tape of this Exchange.

        Tape id of the exchange  # noqa: E501

        :param tape: The tape of this Exchange.  # noqa: E501
        :type: str
        """
        if tape is None:
            raise ValueError("Invalid value for `tape`, must not be `None`")  # noqa: E501

        self._tape = tape

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Exchange, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Exchange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
