# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ForexAggregate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'o': 'int',
        'c': 'int',
        'l': 'int',
        'h': 'int',
        'v': 'int',
        't': 'int'
    }

    attribute_map = {
        'o': 'o',
        'c': 'c',
        'l': 'l',
        'h': 'h',
        'v': 'v',
        't': 't'
    }

    def __init__(self, o=None, c=None, l=None, h=None, v=None, t=None):  # noqa: E501
        """ForexAggregate - a model defined in Swagger"""  # noqa: E501
        self._o = None
        self._c = None
        self._l = None
        self._h = None
        self._v = None
        self._t = None
        self.discriminator = None
        self.o = o
        self.c = c
        self.l = l
        self.h = h
        self.v = v
        self.t = t

    @property
    def o(self):
        """Gets the o of this ForexAggregate.  # noqa: E501

        Open price  # noqa: E501

        :return: The o of this ForexAggregate.  # noqa: E501
        :rtype: int
        """
        return self._o

    @o.setter
    def o(self, o):
        """Sets the o of this ForexAggregate.

        Open price  # noqa: E501

        :param o: The o of this ForexAggregate.  # noqa: E501
        :type: int
        """
        if o is None:
            raise ValueError("Invalid value for `o`, must not be `None`")  # noqa: E501

        self._o = o

    @property
    def c(self):
        """Gets the c of this ForexAggregate.  # noqa: E501

        Close price  # noqa: E501

        :return: The c of this ForexAggregate.  # noqa: E501
        :rtype: int
        """
        return self._c

    @c.setter
    def c(self, c):
        """Sets the c of this ForexAggregate.

        Close price  # noqa: E501

        :param c: The c of this ForexAggregate.  # noqa: E501
        :type: int
        """
        if c is None:
            raise ValueError("Invalid value for `c`, must not be `None`")  # noqa: E501

        self._c = c

    @property
    def l(self):
        """Gets the l of this ForexAggregate.  # noqa: E501

        Low price  # noqa: E501

        :return: The l of this ForexAggregate.  # noqa: E501
        :rtype: int
        """
        return self._l

    @l.setter
    def l(self, l):
        """Sets the l of this ForexAggregate.

        Low price  # noqa: E501

        :param l: The l of this ForexAggregate.  # noqa: E501
        :type: int
        """
        if l is None:
            raise ValueError("Invalid value for `l`, must not be `None`")  # noqa: E501

        self._l = l

    @property
    def h(self):
        """Gets the h of this ForexAggregate.  # noqa: E501

        High price  # noqa: E501

        :return: The h of this ForexAggregate.  # noqa: E501
        :rtype: int
        """
        return self._h

    @h.setter
    def h(self, h):
        """Sets the h of this ForexAggregate.

        High price  # noqa: E501

        :param h: The h of this ForexAggregate.  # noqa: E501
        :type: int
        """
        if h is None:
            raise ValueError("Invalid value for `h`, must not be `None`")  # noqa: E501

        self._h = h

    @property
    def v(self):
        """Gets the v of this ForexAggregate.  # noqa: E501

        Volume of all trades ( Number of bid/asks during this timespan )  # noqa: E501

        :return: The v of this ForexAggregate.  # noqa: E501
        :rtype: int
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this ForexAggregate.

        Volume of all trades ( Number of bid/asks during this timespan )  # noqa: E501

        :param v: The v of this ForexAggregate.  # noqa: E501
        :type: int
        """
        if v is None:
            raise ValueError("Invalid value for `v`, must not be `None`")  # noqa: E501

        self._v = v

    @property
    def t(self):
        """Gets the t of this ForexAggregate.  # noqa: E501

        Timestamp of this aggregation  # noqa: E501

        :return: The t of this ForexAggregate.  # noqa: E501
        :rtype: int
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this ForexAggregate.

        Timestamp of this aggregation  # noqa: E501

        :param t: The t of this ForexAggregate.  # noqa: E501
        :type: int
        """
        if t is None:
            raise ValueError("Invalid value for `t`, must not be `None`")  # noqa: E501

        self._t = t

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ForexAggregate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ForexAggregate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
