# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class HistTrade(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'condition1': 'int',
        'condition2': 'int',
        'condition3': 'int',
        'condition4': 'int',
        'exchange': 'str',
        'price': 'int',
        'size': 'int',
        'timestamp': 'str'
    }

    attribute_map = {
        'condition1': 'condition1',
        'condition2': 'condition2',
        'condition3': 'condition3',
        'condition4': 'condition4',
        'exchange': 'exchange',
        'price': 'price',
        'size': 'size',
        'timestamp': 'timestamp'
    }

    def __init__(self, condition1=None, condition2=None, condition3=None, condition4=None, exchange=None, price=None, size=None, timestamp=None):  # noqa: E501
        """HistTrade - a model defined in Swagger"""  # noqa: E501
        self._condition1 = None
        self._condition2 = None
        self._condition3 = None
        self._condition4 = None
        self._exchange = None
        self._price = None
        self._size = None
        self._timestamp = None
        self.discriminator = None
        self.condition1 = condition1
        self.condition2 = condition2
        self.condition3 = condition3
        self.condition4 = condition4
        self.exchange = exchange
        self.price = price
        self.size = size
        self.timestamp = timestamp

    @property
    def condition1(self):
        """Gets the condition1 of this HistTrade.  # noqa: E501

        Condition 1 of this trade  # noqa: E501

        :return: The condition1 of this HistTrade.  # noqa: E501
        :rtype: int
        """
        return self._condition1

    @condition1.setter
    def condition1(self, condition1):
        """Sets the condition1 of this HistTrade.

        Condition 1 of this trade  # noqa: E501

        :param condition1: The condition1 of this HistTrade.  # noqa: E501
        :type: int
        """
        if condition1 is None:
            raise ValueError("Invalid value for `condition1`, must not be `None`")  # noqa: E501

        self._condition1 = condition1

    @property
    def condition2(self):
        """Gets the condition2 of this HistTrade.  # noqa: E501

        Condition 2 of this trade  # noqa: E501

        :return: The condition2 of this HistTrade.  # noqa: E501
        :rtype: int
        """
        return self._condition2

    @condition2.setter
    def condition2(self, condition2):
        """Sets the condition2 of this HistTrade.

        Condition 2 of this trade  # noqa: E501

        :param condition2: The condition2 of this HistTrade.  # noqa: E501
        :type: int
        """
        if condition2 is None:
            raise ValueError("Invalid value for `condition2`, must not be `None`")  # noqa: E501

        self._condition2 = condition2

    @property
    def condition3(self):
        """Gets the condition3 of this HistTrade.  # noqa: E501

        Condition 3 of this trade  # noqa: E501

        :return: The condition3 of this HistTrade.  # noqa: E501
        :rtype: int
        """
        return self._condition3

    @condition3.setter
    def condition3(self, condition3):
        """Sets the condition3 of this HistTrade.

        Condition 3 of this trade  # noqa: E501

        :param condition3: The condition3 of this HistTrade.  # noqa: E501
        :type: int
        """
        if condition3 is None:
            raise ValueError("Invalid value for `condition3`, must not be `None`")  # noqa: E501

        self._condition3 = condition3

    @property
    def condition4(self):
        """Gets the condition4 of this HistTrade.  # noqa: E501

        Condition 4 of this trade  # noqa: E501

        :return: The condition4 of this HistTrade.  # noqa: E501
        :rtype: int
        """
        return self._condition4

    @condition4.setter
    def condition4(self, condition4):
        """Sets the condition4 of this HistTrade.

        Condition 4 of this trade  # noqa: E501

        :param condition4: The condition4 of this HistTrade.  # noqa: E501
        :type: int
        """
        if condition4 is None:
            raise ValueError("Invalid value for `condition4`, must not be `None`")  # noqa: E501

        self._condition4 = condition4

    @property
    def exchange(self):
        """Gets the exchange of this HistTrade.  # noqa: E501

        The exchange this trade happened on  # noqa: E501

        :return: The exchange of this HistTrade.  # noqa: E501
        :rtype: str
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this HistTrade.

        The exchange this trade happened on  # noqa: E501

        :param exchange: The exchange of this HistTrade.  # noqa: E501
        :type: str
        """
        if exchange is None:
            raise ValueError("Invalid value for `exchange`, must not be `None`")  # noqa: E501

        self._exchange = exchange

    @property
    def price(self):
        """Gets the price of this HistTrade.  # noqa: E501

        Price of the trade  # noqa: E501

        :return: The price of this HistTrade.  # noqa: E501
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this HistTrade.

        Price of the trade  # noqa: E501

        :param price: The price of this HistTrade.  # noqa: E501
        :type: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def size(self):
        """Gets the size of this HistTrade.  # noqa: E501

        Size of the trade  # noqa: E501

        :return: The size of this HistTrade.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this HistTrade.

        Size of the trade  # noqa: E501

        :param size: The size of this HistTrade.  # noqa: E501
        :type: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def timestamp(self):
        """Gets the timestamp of this HistTrade.  # noqa: E501

        Timestamp of this trade  # noqa: E501

        :return: The timestamp of this HistTrade.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this HistTrade.

        Timestamp of this trade  # noqa: E501

        :param timestamp: The timestamp of this HistTrade.  # noqa: E501
        :type: str
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HistTrade, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HistTrade):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
