# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LastTrade(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'price': 'int',
        'size': 'int',
        'exchange': 'int',
        'cond1': 'int',
        'cond2': 'int',
        'cond3': 'int',
        'cond4': 'int',
        'timestamp': 'int'
    }

    attribute_map = {
        'price': 'price',
        'size': 'size',
        'exchange': 'exchange',
        'cond1': 'cond1',
        'cond2': 'cond2',
        'cond3': 'cond3',
        'cond4': 'cond4',
        'timestamp': 'timestamp'
    }

    def __init__(self, price=None, size=None, exchange=None, cond1=None, cond2=None, cond3=None, cond4=None, timestamp=None):  # noqa: E501
        """LastTrade - a model defined in Swagger"""  # noqa: E501
        self._price = None
        self._size = None
        self._exchange = None
        self._cond1 = None
        self._cond2 = None
        self._cond3 = None
        self._cond4 = None
        self._timestamp = None
        self.discriminator = None
        self.price = price
        self.size = size
        self.exchange = exchange
        self.cond1 = cond1
        self.cond2 = cond2
        self.cond3 = cond3
        self.cond4 = cond4
        self.timestamp = timestamp

    @property
    def price(self):
        """Gets the price of this LastTrade.  # noqa: E501

        Price of the trade  # noqa: E501

        :return: The price of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this LastTrade.

        Price of the trade  # noqa: E501

        :param price: The price of this LastTrade.  # noqa: E501
        :type: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def size(self):
        """Gets the size of this LastTrade.  # noqa: E501

        Size of this trade  # noqa: E501

        :return: The size of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this LastTrade.

        Size of this trade  # noqa: E501

        :param size: The size of this LastTrade.  # noqa: E501
        :type: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def exchange(self):
        """Gets the exchange of this LastTrade.  # noqa: E501

        Exchange this trade happened on  # noqa: E501

        :return: The exchange of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this LastTrade.

        Exchange this trade happened on  # noqa: E501

        :param exchange: The exchange of this LastTrade.  # noqa: E501
        :type: int
        """
        if exchange is None:
            raise ValueError("Invalid value for `exchange`, must not be `None`")  # noqa: E501

        self._exchange = exchange

    @property
    def cond1(self):
        """Gets the cond1 of this LastTrade.  # noqa: E501

        Condition 1 of the trade  # noqa: E501

        :return: The cond1 of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._cond1

    @cond1.setter
    def cond1(self, cond1):
        """Sets the cond1 of this LastTrade.

        Condition 1 of the trade  # noqa: E501

        :param cond1: The cond1 of this LastTrade.  # noqa: E501
        :type: int
        """
        if cond1 is None:
            raise ValueError("Invalid value for `cond1`, must not be `None`")  # noqa: E501

        self._cond1 = cond1

    @property
    def cond2(self):
        """Gets the cond2 of this LastTrade.  # noqa: E501

        Condition 2 of the trade  # noqa: E501

        :return: The cond2 of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._cond2

    @cond2.setter
    def cond2(self, cond2):
        """Sets the cond2 of this LastTrade.

        Condition 2 of the trade  # noqa: E501

        :param cond2: The cond2 of this LastTrade.  # noqa: E501
        :type: int
        """
        if cond2 is None:
            raise ValueError("Invalid value for `cond2`, must not be `None`")  # noqa: E501

        self._cond2 = cond2

    @property
    def cond3(self):
        """Gets the cond3 of this LastTrade.  # noqa: E501

        Condition 3 of the trade  # noqa: E501

        :return: The cond3 of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._cond3

    @cond3.setter
    def cond3(self, cond3):
        """Sets the cond3 of this LastTrade.

        Condition 3 of the trade  # noqa: E501

        :param cond3: The cond3 of this LastTrade.  # noqa: E501
        :type: int
        """
        if cond3 is None:
            raise ValueError("Invalid value for `cond3`, must not be `None`")  # noqa: E501

        self._cond3 = cond3

    @property
    def cond4(self):
        """Gets the cond4 of this LastTrade.  # noqa: E501

        Condition 4 of the trade  # noqa: E501

        :return: The cond4 of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._cond4

    @cond4.setter
    def cond4(self, cond4):
        """Sets the cond4 of this LastTrade.

        Condition 4 of the trade  # noqa: E501

        :param cond4: The cond4 of this LastTrade.  # noqa: E501
        :type: int
        """
        if cond4 is None:
            raise ValueError("Invalid value for `cond4`, must not be `None`")  # noqa: E501

        self._cond4 = cond4

    @property
    def timestamp(self):
        """Gets the timestamp of this LastTrade.  # noqa: E501

        Timestamp of this trade  # noqa: E501

        :return: The timestamp of this LastTrade.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this LastTrade.

        Timestamp of this trade  # noqa: E501

        :param timestamp: The timestamp of this LastTrade.  # noqa: E501
        :type: int
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LastTrade, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LastTrade):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
