# coding: utf-8

"""
    Polygon API

    The future of fintech.  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class StocksSnapshotQuote(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'p': 'int',
        's': 'int',
        'p': 'int',
        's': 'int',
        't': 'int'
    }

    attribute_map = {
        'p': 'p',
        's': 's',
        'p': 'P',
        's': 'S',
        't': 't'
    }

    def __init__(self, p=None, s=None, p=None, s=None, t=None):  # noqa: E501
        """StocksSnapshotQuote - a model defined in Swagger"""  # noqa: E501
        self._p = None
        self._s = None
        self._p = None
        self._s = None
        self._t = None
        self.discriminator = None
        self.p = p
        self.s = s
        self.p = p
        self.s = s
        self.t = t

    @property
    def p(self):
        """Gets the p of this StocksSnapshotQuote.  # noqa: E501

        Bid Price  # noqa: E501

        :return: The p of this StocksSnapshotQuote.  # noqa: E501
        :rtype: int
        """
        return self._p

    @p.setter
    def p(self, p):
        """Sets the p of this StocksSnapshotQuote.

        Bid Price  # noqa: E501

        :param p: The p of this StocksSnapshotQuote.  # noqa: E501
        :type: int
        """
        if p is None:
            raise ValueError("Invalid value for `p`, must not be `None`")  # noqa: E501

        self._p = p

    @property
    def s(self):
        """Gets the s of this StocksSnapshotQuote.  # noqa: E501

        Bid size in lots  # noqa: E501

        :return: The s of this StocksSnapshotQuote.  # noqa: E501
        :rtype: int
        """
        return self._s

    @s.setter
    def s(self, s):
        """Sets the s of this StocksSnapshotQuote.

        Bid size in lots  # noqa: E501

        :param s: The s of this StocksSnapshotQuote.  # noqa: E501
        :type: int
        """
        if s is None:
            raise ValueError("Invalid value for `s`, must not be `None`")  # noqa: E501

        self._s = s

    @property
    def p(self):
        """Gets the p of this StocksSnapshotQuote.  # noqa: E501

        Ask Price  # noqa: E501

        :return: The p of this StocksSnapshotQuote.  # noqa: E501
        :rtype: int
        """
        return self._p

    @p.setter
    def p(self, p):
        """Sets the p of this StocksSnapshotQuote.

        Ask Price  # noqa: E501

        :param p: The p of this StocksSnapshotQuote.  # noqa: E501
        :type: int
        """
        if p is None:
            raise ValueError("Invalid value for `p`, must not be `None`")  # noqa: E501

        self._p = p

    @property
    def s(self):
        """Gets the s of this StocksSnapshotQuote.  # noqa: E501

        Ask size in lots  # noqa: E501

        :return: The s of this StocksSnapshotQuote.  # noqa: E501
        :rtype: int
        """
        return self._s

    @s.setter
    def s(self, s):
        """Sets the s of this StocksSnapshotQuote.

        Ask size in lots  # noqa: E501

        :param s: The s of this StocksSnapshotQuote.  # noqa: E501
        :type: int
        """
        if s is None:
            raise ValueError("Invalid value for `s`, must not be `None`")  # noqa: E501

        self._s = s

    @property
    def t(self):
        """Gets the t of this StocksSnapshotQuote.  # noqa: E501

        Last Updated timestamp ( Nanosecond Timestamp )  # noqa: E501

        :return: The t of this StocksSnapshotQuote.  # noqa: E501
        :rtype: int
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this StocksSnapshotQuote.

        Last Updated timestamp ( Nanosecond Timestamp )  # noqa: E501

        :param t: The t of this StocksSnapshotQuote.  # noqa: E501
        :type: int
        """
        if t is None:
            raise ValueError("Invalid value for `t`, must not be `None`")  # noqa: E501

        self._t = t

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StocksSnapshotQuote, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StocksSnapshotQuote):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
